function decryptedBlock = decryptBlock(cipherBlockBytes, roundKeys)
%AES.DECRYPTBLOCK AES-128 block decryption (one 16-byte block).
%
%   decryptedBlock = aes.decryptBlock(cipherBlockBytes, roundKeys)
%
%   cipherBlockBytes must be a 16-byte uint8 vector.
%   roundKeys is the 4×44 uint8 matrix generated by aes.keyExpansion.

    if ~isa(cipherBlockBytes, 'uint8') || numel(cipherBlockBytes) ~= 16
        error('decryptBlock:InvalidBlock', ...
              'AES block must be exactly 16 bytes (uint8).');
    end

    % reshape into 4×4 state matrix
    state = reshape(cipherBlockBytes, 4, []);

    % AES parameters
    Nr = 10;

    % Initial AddRoundKey (last round key)
    keyStart = Nr * 4 + 1;
    state = addRoundKey(state, roundKeys(:, keyStart:keyStart+3));

    % Main inverse rounds (9 rounds)
    for roundIndex = (Nr-1):-1:1
        state = invShiftRows(state);
        state = invSubBytes(state);

        keyStart = roundIndex * 4 + 1;
        state = addRoundKey(state, roundKeys(:, keyStart:keyStart+3));

        state = invMixColumns(state);
    end

    % Final inverse round (no InvMixColumns)
    state = invShiftRows(state);
    state = invSubBytes(state);
    state = addRoundKey(state, roundKeys(:, 1:4));

    decryptedBlock = reshape(state, 1, 16);
end


% ------------------ Inverse helper functions ------------------

function out = addRoundKey(state, keyWords)
    out = bitxor(state, keyWords);
end

function out = invShiftRows(state)
    out = state;
    out(2, :) = circshift(out(2, :), [0 1]);
    out(3, :) = circshift(out(3, :), [0 2]);
    out(4, :) = circshift(out(4, :), [0 3]);
end

function out = invSubBytes(state)
    out = uint8(aes_inv_sbox_lookup(double(state) + 1));
end

function out = invMixColumns(state)
    out = zeros(4,4,'uint8');
    for col = 1:4
        a = state(:,col);
        out(:,col) = [ ...
            bitxor(bitxor(bitxor(xt(a(1),14), xt(a(2),11)), xt(a(3),13)), xt(a(4),9)); ...
            bitxor(bitxor(bitxor(xt(a(1),9),  xt(a(2),14)), xt(a(3),11)), xt(a(4),13)); ...
            bitxor(bitxor(bitxor(xt(a(1),13), xt(a(2),9)),  xt(a(3),14)), xt(a(4),11)); ...
            bitxor(bitxor(bitxor(xt(a(1),11), xt(a(2),13)), xt(a(3),9)),  xt(a(4),14)) ...
        ];
    end
end

function y = xt(x, multiplier)
    switch multiplier
        case 9
            y = xtime_chain(x, [2 2 2 1]);   % 2×2×2×x ⊕ x
        case 11
            y = xtime_chain(x, [2 2 2])     % 2×2×2×x ⊕ 2×x ⊕ x
                 ; y = bitxor(y, xtime_chain(x, [2])); y = bitxor(y, x);
        case 13
            y = xtime_chain(x, [2 2 2])     % 2×2×2×x ⊕ 2×2×x ⊕ x
                 ; y = bitxor(y, xtime_chain(x, [2 2])); y = bitxor(y, x);
        case 14
            y = xtime_chain(x, [2 2 2])     % 2×2×2×x ⊕ 2×2×x ⊕ 2×x
                 ; y = bitxor(y, xtime_chain(x, [2 2])); y = bitxor(y, xtime_chain(x, [2]));
        otherwise
            error('Invalid multiplier');
    end
end

function y = xtime_chain(x, multipliers)
    y = x;
    for m = multipliers
        y = aes_xtime(y);
    end
end

function out = aes_inv_sbox_lookup(indices)
    persistent invS
    if isempty(invS)
        invS = uint8([
        82  9 106 213  48  54 165  56 191  64 163 158 129 243 215 251 ...
        124 227  57 130 155  47 255 135  52 142  67  68 196 222 233   5 ...
        54  63  15  45  239  44  34 214  234  23  19  21  122  32  29 ...
        202  63  181 120  15  45  239  44  34 214  234  23  19  21  122 ...
        32  29  223 155  14  94  33  34  87  53  255  12  11  183  78  25 ...
        242  132  13  73  98  141  190 111  52  88  28  42  196  54  175 ...
         73  111  112  62  181  132  98  11 215  41  205 201  125 211  43  110 ...
        91  122  41  147  16  10 215  202  69  126  51  205  142  77  157  69 ...
        74  100  23  83 158 165  29  41 215  90  61  106  45 199  125 171 ...
        181 222  20  81  41  196  115  84 244 239  72  46  78  175  233  69 ...
        33  189  12  96 164  151 188 133 197 241  82 112  75 135 160 137 ...
        70  39  187  246 166  65  93  55  199 174  193 168  130 222  27 ...
        119 193  44  12  254  129  240  50 116 253  87 126 222  166  170  68 ...
        96  16  55 112  206  157 104  128  140  189 241  50 190 126 122 233 ...
        139  235  228  66  25 189 155  157 233 127  147  241  166  255  221 ...
        71 248  46  195  179  86  26  67  99  63  33  188  164 137 192  38]);
    end
    out = invS(indices);
end

function out = aes_xtime(x)
    out = bitshift(x,1);
    if bitget(x,8)
        out = bitxor(out, 27);
    end
    out = bitand(out,255);
end
